deploy-job:
  tags:
      - hva
  image: mcr.microsoft.com/azure-cli
  stage: deploy  
  script:    
  - az login     
  - az account set --subscription " ***** "    
  - az group list
  - az webapp up --runtime PYTHON:3.11 --sku B1 --logs